import java.sql.*;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Mark Anthony
 */
public class vendingMachinePOS extends javax.swing.JFrame {

    /**
     * Creates new form vendingMachinePOS
     */
    public vendingMachinePOS() {
        initComponents();
    }
    
    Connection con;
    PreparedStatement pst;
    
    public void Connect(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con= DriverManager.getConnection("jdbc:mysql://localhost/vendingmachine","root","");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(vendingMachinePOS.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(vendingMachinePOS.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private final Map<String, Integer> productCounts = new HashMap<>();
    public void addTable (String pName,double price){
        
        DefaultTableModel df= (DefaultTableModel) jTable1.getModel();
        
        Vector v=new Vector();
        
        
        v.add(pName);
        v.add(price);
        
        df.addRow(v);
        }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jB6 = new javax.swing.JButton();
        jB9 = new javax.swing.JButton();
        jB7 = new javax.swing.JButton();
        jB5 = new javax.swing.JButton();
        jB2 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jB3 = new javax.swing.JButton();
        jBtOk = new javax.swing.JButton();
        jB0 = new javax.swing.JButton();
        jTextPayment = new javax.swing.JTextField();
        jTxt1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jB8 = new javax.swing.JButton();
        jBtP1 = new javax.swing.JButton();
        jB4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabelcoke = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextcoke = new javax.swing.JTextField();
        jLabelcoke4 = new javax.swing.JLabel();
        jLabelcoke5 = new javax.swing.JLabel();
        jTextcoke1 = new javax.swing.JTextField();
        jTextcoke2 = new javax.swing.JTextField();
        jTextcoke6 = new javax.swing.JTextField();
        jTextcoke7 = new javax.swing.JTextField();
        jLabelcoke9 = new javax.swing.JLabel();
        jLabelcoke10 = new javax.swing.JLabel();
        jLabelcoke11 = new javax.swing.JLabel();
        jTextcoke8 = new javax.swing.JTextField();
        jLabelcoke18 = new javax.swing.JLabel();
        jTextcoke15 = new javax.swing.JTextField();
        jLabelcoke19 = new javax.swing.JLabel();
        jLabelcoke20 = new javax.swing.JLabel();
        jLabelcoke21 = new javax.swing.JLabel();
        jLabelcoke22 = new javax.swing.JLabel();
        jLabelcoke23 = new javax.swing.JLabel();
        jLabelcoke24 = new javax.swing.JLabel();
        jLabelcoke25 = new javax.swing.JLabel();
        jTextcoke16 = new javax.swing.JTextField();
        jTextcoke17 = new javax.swing.JTextField();
        jTextcoke18 = new javax.swing.JTextField();
        jTextcoke19 = new javax.swing.JTextField();
        jTextcoke20 = new javax.swing.JTextField();
        jTextcoke21 = new javax.swing.JTextField();
        jTextcoke22 = new javax.swing.JTextField();
        jLabelcoke6 = new javax.swing.JLabel();
        jLabelcoke7 = new javax.swing.JLabel();
        jLabelcoke8 = new javax.swing.JLabel();
        jLabelcoke12 = new javax.swing.JLabel();
        jLabelcoke13 = new javax.swing.JLabel();
        jLabelcoke14 = new javax.swing.JLabel();
        jLabelcoke26 = new javax.swing.JLabel();
        jTextcoke23 = new javax.swing.JTextField();
        jTextcoke9 = new javax.swing.JTextField();
        jTextcoke10 = new javax.swing.JTextField();
        jTextcoke11 = new javax.swing.JTextField();
        jTextcoke3 = new javax.swing.JTextField();
        jTextcoke4 = new javax.swing.JTextField();
        jTextcoke5 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 153, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 255, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SMART REFRESMENTS VENDING MACHINE");
        jLabel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1)));
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setDebugGraphicsOptions(javax.swing.DebugGraphics.FLASH_OPTION);
        jLabel1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jLabel1ComponentAdded(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 1040, 80));

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Insert Coin");

        jB6.setBackground(new java.awt.Color(153, 153, 153));
        jB6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jB6.setText("6");
        jB6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB6ActionPerformed(evt);
            }
        });

        jB9.setBackground(new java.awt.Color(153, 153, 153));
        jB9.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jB9.setText("9");
        jB9.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jB9.setInheritsPopupMenu(true);
        jB9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB9ActionPerformed(evt);
            }
        });

        jB7.setBackground(new java.awt.Color(153, 153, 153));
        jB7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jB7.setText("7");
        jB7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB7ActionPerformed(evt);
            }
        });

        jB5.setBackground(new java.awt.Color(153, 153, 153));
        jB5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jB5.setText("5");
        jB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB5ActionPerformed(evt);
            }
        });

        jB2.setBackground(new java.awt.Color(153, 153, 153));
        jB2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jB2.setText("2");
        jB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB2ActionPerformed(evt);
            }
        });

        jButton15.setBackground(new java.awt.Color(153, 153, 153));
        jButton15.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        jButton15.setText("clear");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jB3.setBackground(new java.awt.Color(153, 153, 153));
        jB3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jB3.setText("3");
        jB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB3ActionPerformed(evt);
            }
        });

        jBtOk.setBackground(new java.awt.Color(153, 153, 153));
        jBtOk.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jBtOk.setText("Ok");
        jBtOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtOkActionPerformed(evt);
            }
        });

        jB0.setBackground(new java.awt.Color(153, 153, 153));
        jB0.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jB0.setText("0");
        jB0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB0ActionPerformed(evt);
            }
        });

        jTextPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPaymentActionPerformed(evt);
            }
        });

        jTxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxt1ActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(153, 255, 153));
        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jLabel3.setText("Selected products");

        jB8.setBackground(new java.awt.Color(153, 153, 153));
        jB8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jB8.setText("8");
        jB8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB8ActionPerformed(evt);
            }
        });

        jBtP1.setBackground(new java.awt.Color(153, 153, 153));
        jBtP1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jBtP1.setText("1");
        jBtP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtP1ActionPerformed(evt);
            }
        });

        jB4.setBackground(new java.awt.Color(153, 153, 153));
        jB4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jB4.setText("4");
        jB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB4ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product", "Price"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Admin \n Log in");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("jButton1");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("jButton1");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jB4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtOk, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtP1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jB2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB8, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB0, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jB3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxt1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jTextPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 66, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(146, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jB3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jB5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jB8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jB0, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jBtOk, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtP1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jB2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(564, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(16, 16, 16)))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 10, 260, 620));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("7");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, 30, 30));

        jLabelcoke.setBackground(new java.awt.Color(255, 255, 255));
        jLabelcoke.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mark Anthony\\OneDrive\\Documents\\OOP\\VendingMachine\\src\\images\\cobra.png")); // NOI18N
        jLabelcoke.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.red, java.awt.Color.yellow));
        jPanel1.add(jLabelcoke, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 160));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("1");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 30, 30));

        jTextcoke.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jTextcoke.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextcoke.setText("20");
        jPanel1.add(jTextcoke, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, -1, -1));

        jLabelcoke4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mark Anthony\\OneDrive\\Pictures\\def.png")); // NOI18N
        jLabelcoke4.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.red, java.awt.Color.yellow));
        jPanel1.add(jLabelcoke4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, 160));

        jLabelcoke5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mark Anthony\\OneDrive\\Documents\\OOP\\VendingMachine\\src\\images\\royal.png")); // NOI18N
        jLabelcoke5.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.red, java.awt.Color.yellow));
        jPanel1.add(jLabelcoke5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, 160));

        jTextcoke1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jTextcoke1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextcoke1.setText("20");
        jPanel1.add(jTextcoke1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        jTextcoke2.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jTextcoke2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextcoke2.setText("20");
        jPanel1.add(jTextcoke2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, -1, -1));

        jTextcoke6.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jTextcoke6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextcoke6.setText("20");
        jPanel1.add(jTextcoke6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, -1, -1));

        jTextcoke7.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jTextcoke7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextcoke7.setText("20");
        jPanel1.add(jTextcoke7, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 180, -1, -1));

        jLabelcoke9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mark Anthony\\OneDrive\\Documents\\OOP\\VendingMachine\\src\\images\\rc.png")); // NOI18N
        jLabelcoke9.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.red, java.awt.Color.yellow));
        jPanel1.add(jLabelcoke9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, -1, 160));

        jLabelcoke10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mark Anthony\\OneDrive\\Documents\\OOP\\VendingMachine\\src\\images\\pepsi1.png")); // NOI18N
        jLabelcoke10.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.red, java.awt.Color.yellow));
        jPanel1.add(jLabelcoke10, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, -1, 160));

        jLabelcoke11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mark Anthony\\OneDrive\\Documents\\OOP\\VendingMachine\\src\\images\\sprite1.png")); // NOI18N
        jLabelcoke11.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.red, java.awt.Color.yellow));
        jPanel1.add(jLabelcoke11, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, 120, 160));

        jTextcoke8.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jTextcoke8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextcoke8.setText("20");
        jPanel1.add(jTextcoke8, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 180, -1, -1));

        jLabelcoke18.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mark Anthony\\OneDrive\\Documents\\OOP\\VendingMachine\\src\\images\\coke.png")); // NOI18N
        jLabelcoke18.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.red, java.awt.Color.yellow));
        jPanel1.add(jLabelcoke18, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, 110, 160));

        jTextcoke15.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jTextcoke15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextcoke15.setText("20");
        jPanel1.add(jTextcoke15, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 180, -1, -1));

        jLabelcoke19.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mark Anthony\\OneDrive\\Documents\\OOP\\VendingMachine\\src\\images\\minute maid.png")); // NOI18N
        jLabelcoke19.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.red, java.awt.Color.yellow));
        jPanel1.add(jLabelcoke19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, -1, 160));

        jLabelcoke20.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mark Anthony\\OneDrive\\Documents\\OOP\\VendingMachine\\src\\images\\rh.png")); // NOI18N
        jLabelcoke20.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.red, java.awt.Color.yellow));
        jPanel1.add(jLabelcoke20, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, -1, 160));

        jLabelcoke21.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mark Anthony\\OneDrive\\Documents\\OOP\\VendingMachine\\src\\images\\gin.png")); // NOI18N
        jLabelcoke21.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.red, java.awt.Color.yellow));
        jPanel1.add(jLabelcoke21, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, -1, 160));

        jLabelcoke22.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mark Anthony\\OneDrive\\Documents\\OOP\\VendingMachine\\src\\images\\the bar.png")); // NOI18N
        jLabelcoke22.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.red, java.awt.Color.yellow));
        jPanel1.add(jLabelcoke22, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 450, -1, 160));

        jLabelcoke23.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mark Anthony\\OneDrive\\Documents\\OOP\\VendingMachine\\src\\images\\gatorade bl.png")); // NOI18N
        jLabelcoke23.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.red, java.awt.Color.yellow));
        jPanel1.add(jLabelcoke23, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 450, -1, 160));

        jLabelcoke24.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mark Anthony\\OneDrive\\Documents\\OOP\\VendingMachine\\src\\images\\gatorade ornge.png")); // NOI18N
        jLabelcoke24.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.red, java.awt.Color.yellow));
        jPanel1.add(jLabelcoke24, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 450, -1, 160));

        jLabelcoke25.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mark Anthony\\OneDrive\\Documents\\OOP\\VendingMachine\\src\\images\\gatorade violet.png")); // NOI18N
        jLabelcoke25.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.red, java.awt.Color.yellow));
        jPanel1.add(jLabelcoke25, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 450, -1, 160));

        jTextcoke16.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jTextcoke16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextcoke16.setText("20");
        jPanel1.add(jTextcoke16, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 620, -1, -1));

        jTextcoke17.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jTextcoke17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextcoke17.setText("20");
        jPanel1.add(jTextcoke17, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 620, -1, -1));

        jTextcoke18.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jTextcoke18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextcoke18.setText("20");
        jPanel1.add(jTextcoke18, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 620, -1, -1));

        jTextcoke19.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jTextcoke19.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextcoke19.setText("20");
        jPanel1.add(jTextcoke19, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 620, -1, -1));

        jTextcoke20.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jTextcoke20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextcoke20.setText("20");
        jPanel1.add(jTextcoke20, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 620, -1, -1));

        jTextcoke21.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jTextcoke21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextcoke21.setText("20");
        jPanel1.add(jTextcoke21, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 620, -1, -1));

        jTextcoke22.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jTextcoke22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextcoke22.setText("20");
        jPanel1.add(jTextcoke22, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 620, -1, -1));

        jLabelcoke6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mark Anthony\\OneDrive\\Documents\\OOP\\VendingMachine\\src\\images\\sting.png")); // NOI18N
        jLabelcoke6.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.red, java.awt.Color.yellow));
        jPanel1.add(jLabelcoke6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, 160));

        jLabelcoke7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mark Anthony\\OneDrive\\Documents\\OOP\\VendingMachine\\src\\images\\natures spring 500ml.png")); // NOI18N
        jLabelcoke7.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.red, java.awt.Color.yellow));
        jPanel1.add(jLabelcoke7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 120, 160));

        jLabelcoke8.setBackground(new java.awt.Color(204, 255, 255));
        jLabelcoke8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mark Anthony\\OneDrive\\Documents\\OOP\\VendingMachine\\src\\images\\summit 1l.png")); // NOI18N
        jLabelcoke8.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.red, java.awt.Color.yellow));
        jPanel1.add(jLabelcoke8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 120, 160));

        jLabelcoke12.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mark Anthony\\OneDrive\\Documents\\OOP\\VendingMachine\\src\\images\\cobra red.png")); // NOI18N
        jLabelcoke12.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.red, java.awt.Color.yellow));
        jPanel1.add(jLabelcoke12, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 120, 160));

        jLabelcoke13.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mark Anthony\\OneDrive\\Documents\\OOP\\VendingMachine\\src\\images\\summit 350ml.png")); // NOI18N
        jLabelcoke13.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.red, java.awt.Color.yellow));
        jPanel1.add(jLabelcoke13, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 220, -1, 160));

        jLabelcoke14.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mark Anthony\\OneDrive\\Documents\\OOP\\VendingMachine\\src\\images\\absolute 350.png")); // NOI18N
        jLabelcoke14.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.red, java.awt.Color.yellow));
        jPanel1.add(jLabelcoke14, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 220, -1, 160));

        jLabelcoke26.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mark Anthony\\OneDrive\\Documents\\OOP\\VendingMachine\\src\\images\\c2.png")); // NOI18N
        jLabelcoke26.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.red, java.awt.Color.yellow));
        jPanel1.add(jLabelcoke26, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 220, -1, 160));

        jTextcoke23.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jTextcoke23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextcoke23.setText("20");
        jPanel1.add(jTextcoke23, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 390, -1, -1));

        jTextcoke9.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jTextcoke9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextcoke9.setText("20");
        jPanel1.add(jTextcoke9, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 390, -1, -1));

        jTextcoke10.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jTextcoke10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextcoke10.setText("20");
        jPanel1.add(jTextcoke10, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, -1, -1));

        jTextcoke11.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jTextcoke11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextcoke11.setText("20");
        jPanel1.add(jTextcoke11, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 390, -1, -1));

        jTextcoke3.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jTextcoke3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextcoke3.setText("20");
        jPanel1.add(jTextcoke3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, -1, -1));

        jTextcoke4.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jTextcoke4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextcoke4.setText("20");
        jPanel1.add(jTextcoke4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, -1, -1));

        jTextcoke5.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jTextcoke5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextcoke5.setText("20");
        jPanel1.add(jTextcoke5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("2");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 30, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("4");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 30, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("5");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 30, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("6");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, 30, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("3");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 30, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("8");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 30, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("8");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 30, 30));

        jScrollPane2.setViewportView(jPanel1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1100, 530));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jLabel1ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1ComponentAdded

    private void jTextPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPaymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPaymentActionPerformed

    private void jB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB5ActionPerformed
         String enterNum = jTxt1.getText();
      
      if(enterNum==""){
          jTxt1.setText(jBtP1.getText());
          
      }else{
          enterNum = jTxt1.getText()+ jBtP1.getText();
         jTxt1.setText(enterNum);
      }
    }//GEN-LAST:event_jB5ActionPerformed

    private void jTxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxt1ActionPerformed
        
             
            
        
    }//GEN-LAST:event_jTxt1ActionPerformed

    private void jBtP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtP1ActionPerformed
      String enterNum = jTxt1.getText();
      
      if(enterNum==""){
          jTxt1.setText(jBtP1.getText());
          
      }else{
          enterNum = jTxt1.getText()+ jBtP1.getText();
         jTxt1.setText(enterNum);
      }
      
   
    }//GEN-LAST:event_jBtP1ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
       jTxt1.setText("");
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB2ActionPerformed
        // TODO add your handling code here:
         String enterNum = jTxt1.getText();
      
      if(enterNum==""){
          jTxt1.setText(jBtP1.getText());
          
      }else{
          enterNum = jTxt1.getText()+ jB2.getText();
         jTxt1.setText(enterNum);
      }
    }//GEN-LAST:event_jB2ActionPerformed

    private void jB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB3ActionPerformed
         String enterNum = jTxt1.getText();
      
      if(enterNum==""){
          jTxt1.setText(jBtP1.getText());
          
      }else{
          enterNum = jTxt1.getText()+ jB3.getText();
         jTxt1.setText(enterNum);
      }
    }//GEN-LAST:event_jB3ActionPerformed

    private void jB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB4ActionPerformed
        String enterNum = jTxt1.getText();
      
      if(enterNum==""){
          jTxt1.setText(jBtP1.getText());
          
      }else{
          enterNum = jTxt1.getText()+ jB4.getText();
         jTxt1.setText(enterNum);
      }
    }//GEN-LAST:event_jB4ActionPerformed

    private void jB6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB6ActionPerformed
        String enterNum = jTxt1.getText();
      
      if(enterNum==""){
          jTxt1.setText(jBtP1.getText());
          
      }else{
          enterNum = jTxt1.getText()+ jB6.getText();
         jTxt1.setText(enterNum);
      }
    }//GEN-LAST:event_jB6ActionPerformed

    private void jB7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB7ActionPerformed
         String enterNum = jTxt1.getText();
      
      if(enterNum==""){
          jTxt1.setText(jBtP1.getText());
          
      }else{
          enterNum = jTxt1.getText()+ jB7.getText();
         jTxt1.setText(enterNum);
      }
    }//GEN-LAST:event_jB7ActionPerformed

    private void jB8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB8ActionPerformed
        String enterNum = jTxt1.getText();
      
      if(enterNum==""){
          jTxt1.setText(jBtP1.getText());
          
      }else{
          enterNum = jTxt1.getText()+ jB8.getText();
         jTxt1.setText(enterNum);
      }
    }//GEN-LAST:event_jB8ActionPerformed

    private void jB9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB9ActionPerformed
        String enterNum = jTxt1.getText();
      
      if(enterNum==""){
          jTxt1.setText(jBtP1.getText());
          
      }else{
          enterNum = jTxt1.getText()+ jB9.getText();
         jTxt1.setText(enterNum);
      }
    }//GEN-LAST:event_jB9ActionPerformed

    private void jB0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB0ActionPerformed
         String enterNum = jTxt1.getText();
      
      if(enterNum==""){
          jTxt1.setText(jBtP1.getText());
          
      }else{
          enterNum = jTxt1.getText()+ jB0.getText();
         jTxt1.setText(enterNum);
      }
    }//GEN-LAST:event_jB0ActionPerformed

    private void jBtOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtOkActionPerformed
            String url = "jdbc:mysql://localhost:3306/vendingmachine";
         String sUser = "root";
         String sPass = "";  
         
    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
    Connection con = DriverManager.getConnection(url, sUser, sPass);
    Statement st = con.createStatement();
    
        String prod_name = "coke";
        String qty = "20"; // This could be dynamically set based on user selection
        String price = "30";
        
        pst = con.prepareStatement("INSERT INTO products(prod_name, qty, price) VALUES (?, ?, ?)");
        pst.setString(1, prod_name);
        pst.setString(2, qty);
        pst.setString(3, price);
        
        int k = pst.executeUpdate();
        
        if (jTxt1.getText().equals("11")) {
            // Assuming 'jTextcoke' represents the stock in the user interface
            int currentStock = Integer.parseInt(jTextcoke.getText());
            currentStock--; // Decrease stock by 1 for "Coke Zero"
            jTextcoke.setText(Integer.toString(currentStock)); // Update the displayed stock
            
            // Here you might want to update the database stock for "Coke Zero"
            // For example, if 'currentStock' represents the updated stock value, you could perform an update query
            // An update query might look like:
            // pst = con.prepareStatement("UPDATE product SET qty = ? WHERE prod_name = ?");
            // pst.setInt(1, currentStock);
            // pst.setString(2, "Coke Zero");
            // pst.executeUpdate();
        }
        
    } catch (SQLException ex) {
        Logger.getLogger(vendingMachinePOS.class.getName()).log(Level.SEVERE, null, ex);
    }   catch (ClassNotFoundException ex) {
            Logger.getLogger(vendingMachinePOS.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jBtOkActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     LogIn lg= new LogIn();
     lg.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        int result = JOptionPane.showConfirmDialog(this, "Do you really want to exit?", "Confirm Exit?", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
             // user clicked Yes, so exit the application
             System.exit(0);
        } else {
         // user clicked No, so do nothing
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vendingMachinePOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vendingMachinePOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vendingMachinePOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vendingMachinePOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vendingMachinePOS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB0;
    private javax.swing.JButton jB2;
    private javax.swing.JButton jB3;
    private javax.swing.JButton jB4;
    private javax.swing.JButton jB5;
    private javax.swing.JButton jB6;
    private javax.swing.JButton jB7;
    private javax.swing.JButton jB8;
    private javax.swing.JButton jB9;
    private javax.swing.JButton jBtOk;
    private javax.swing.JButton jBtP1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelcoke;
    private javax.swing.JLabel jLabelcoke10;
    private javax.swing.JLabel jLabelcoke11;
    private javax.swing.JLabel jLabelcoke12;
    private javax.swing.JLabel jLabelcoke13;
    private javax.swing.JLabel jLabelcoke14;
    private javax.swing.JLabel jLabelcoke18;
    private javax.swing.JLabel jLabelcoke19;
    private javax.swing.JLabel jLabelcoke20;
    private javax.swing.JLabel jLabelcoke21;
    private javax.swing.JLabel jLabelcoke22;
    private javax.swing.JLabel jLabelcoke23;
    private javax.swing.JLabel jLabelcoke24;
    private javax.swing.JLabel jLabelcoke25;
    private javax.swing.JLabel jLabelcoke26;
    private javax.swing.JLabel jLabelcoke4;
    private javax.swing.JLabel jLabelcoke5;
    private javax.swing.JLabel jLabelcoke6;
    private javax.swing.JLabel jLabelcoke7;
    private javax.swing.JLabel jLabelcoke8;
    private javax.swing.JLabel jLabelcoke9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextPayment;
    private javax.swing.JTextField jTextcoke;
    private javax.swing.JTextField jTextcoke1;
    private javax.swing.JTextField jTextcoke10;
    private javax.swing.JTextField jTextcoke11;
    private javax.swing.JTextField jTextcoke15;
    private javax.swing.JTextField jTextcoke16;
    private javax.swing.JTextField jTextcoke17;
    private javax.swing.JTextField jTextcoke18;
    private javax.swing.JTextField jTextcoke19;
    private javax.swing.JTextField jTextcoke2;
    private javax.swing.JTextField jTextcoke20;
    private javax.swing.JTextField jTextcoke21;
    private javax.swing.JTextField jTextcoke22;
    private javax.swing.JTextField jTextcoke23;
    private javax.swing.JTextField jTextcoke3;
    private javax.swing.JTextField jTextcoke4;
    private javax.swing.JTextField jTextcoke5;
    private javax.swing.JTextField jTextcoke6;
    private javax.swing.JTextField jTextcoke7;
    private javax.swing.JTextField jTextcoke8;
    private javax.swing.JTextField jTextcoke9;
    private javax.swing.JTextField jTxt1;
    // End of variables declaration//GEN-END:variables
}
